# @name get-prompts
GET http://localhost:3330/prompts

###

# @name upload
POST http://localhost:3330/files
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="anders.mp3"
Content-Type: audio/mpeg

< ~/Downloads/anders-da2.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3330/files/4683368e-fcb5-481b-a068-0b812d3517ec/transcription
Content-Type: application/json

{
    "prompt": "sanctum, healing, salvation, threaten"
}

###

# @name generate-ai-completion
POST http://localhost:3330/ai/generate
Content-Type: application/json

{
    "fileId": "4683368e-fcb5-481b-a068-0b812d3517ec",
    "template": "Generate a succint description for the following video transcript: '''{transcription}'''"
}
